"""alterando banco, professor e prof orientador

Revision ID: 1e59a4f4dd66
Revises: 
Create Date: 2026-02-03 14:11:03.523788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e59a4f4dd66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('funcao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_lecionada', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_disciplina',
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'disciplina_id')
    )
    op.create_table('grupos_estudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criador_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_disciplina',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'disciplina_id')
    )
    op.create_table('professoresOrientadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_orientação', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_orientação'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_grupo_estudo',
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('grupo_estudo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['grupo_estudo_id'], ['grupos_estudo.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'grupo_estudo_id')
    )
    op.create_table('professor_orientador_disciplina',
    sa.Column('professor_orientador_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['professor_orientador_id'], ['professoresOrientadores.id'], ),
    sa.PrimaryKeyConstraint('professor_orientador_id', 'disciplina_id')
    )
    op.create_table('tutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(length=100), nullable=True),
    sa.Column('id_disciplina', sa.Integer(), nullable=False),
    sa.Column('id_professorOrientador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['id_professorOrientador'], ['professoresOrientadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessoes_tutoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('professor_orientador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professor_orientador_id'], ['professoresOrientadores.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor_servidor_etep',
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('servidor_etep_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servidor_etep_id'], ['servidores.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], ),
    sa.PrimaryKeyConstraint('tutor_id', 'servidor_etep_id')
    )
    op.create_table('aluno_sessao_tutoria',
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('sessao_tutoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['sessao_tutoria_id'], ['sessoes_tutoria.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'sessao_tutoria_id')
    )
    op.create_table('servidor_etep_sessao_tutoria',
    sa.Column('sessao_tutoria_id', sa.Integer(), nullable=False),
    sa.Column('servidor_etep_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servidor_etep_id'], ['servidores.id'], ),
    sa.ForeignKeyConstraint(['sessao_tutoria_id'], ['sessoes_tutoria.id'], ),
    sa.PrimaryKeyConstraint('sessao_tutoria_id', 'servidor_etep_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servidor_etep_sessao_tutoria')
    op.drop_table('aluno_sessao_tutoria')
    op.drop_table('tutor_servidor_etep')
    op.drop_table('sessoes_tutoria')
    op.drop_table('tutores')
    op.drop_table('professor_orientador_disciplina')
    op.drop_table('aluno_grupo_estudo')
    op.drop_table('professoresOrientadores')
    op.drop_table('professor_disciplina')
    op.drop_table('grupos_estudo')
    op.drop_table('aluno_disciplina')
    op.drop_table('servidores')
    op.drop_table('professores')
    op.drop_table('alunos')
    op.drop_table('usuarios')
    op.drop_table('disciplinas')
    # ### end Alembic commands ###
